Functions
1. Define the function
2. Invoking the fucnction
3. Passing the arguments

In [ ]:
def cake_baker(p,f,s):
  print("No of pieces =",p)
  print("Flavour is=",f)
  print("size is=",s)

cake_baker("5","Choclate","2Kg")
cake_baker("100","vanilla","3kg")

No of pieces = 5
Flavour is= Choclate
size is= 2Kg
No of pieces = 100
Flavour is= vanilla
size is= 3kg


Args


In [ ]:
def add(*bunch):
  sum=0
  for i in bunch:
    sum+=i
  return sum
print(add(1,2,3,4,5))

15


Kwargs

In [ ]:
def greet(**kwargs):
  print("Hello")
  for key,value in kwargs.items():
    print(value,end=" ")

greet(name="Gouri",usn="gn131032",branch="ECE")

Hello
Gouri gn131032 ECE 

In [ ]:
import random

x=random.randint(1,9)
print(x)

a=random.random()
print(a)

9
0.5726734519303192


In [ ]:
import random

computer=random.randint(1,9)
userinput=int(input(" Enter the number between 1 and 9  "))
print(computer)
print(userinput)

if computer>userinput:
  print("Computer Won")
elif computer==userinput:
  print("TIE")
else:
  print("You won")

 Enter the number between 1 and 9  9
5
9
You won


In [3]:
import random

gamelist=['rock','paper','scissors']
comp=random.choice(gamelist)
user=input("Enter either rock or paper or scissors   ")
print(comp)
print(user)

if (comp=="rock" and user=="paper"):
  print("computer won")
elif (comp=="paper" and user=="scissors"):
  print("You won")
elif (comp=="scissors" and user=="paper"):
  print("Computer won")

else:
  print("TIE")

Enter either rock or paper or scissors   scissors
paper
scissors
You won


NumPy- Numerical python

In [4]:
import numpy as np

In [8]:
a=np.array([35,1,34,36,27,48,49])
print(type(a))

b=np.zeros(3)
c=np.ones(4)

print(b)
print(c)

d=np.sort(a)
print(d)

<class 'numpy.ndarray'>
[0. 0. 0.]
[1. 1. 1. 1.]
[ 1 27 34 35 36 48 49]
